//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_Cloud_Tuandcpk00260_.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.bus_dataSoap")]
    public interface bus_dataSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getdata", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getdata(string cmd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getdata", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getdataAsync(string cmd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/excutedata", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string excutedata(string cmd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/excutedata", ReplyAction="*")]
        System.Threading.Tasks.Task<string> excutedataAsync(string cmd);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface bus_dataSoapChannel : App_Cloud_Tuandcpk00260_.ServiceReference1.bus_dataSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class bus_dataSoapClient : System.ServiceModel.ClientBase<App_Cloud_Tuandcpk00260_.ServiceReference1.bus_dataSoap>, App_Cloud_Tuandcpk00260_.ServiceReference1.bus_dataSoap {
        
        public bus_dataSoapClient() {
        }
        
        public bus_dataSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public bus_dataSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public bus_dataSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public bus_dataSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet getdata(string cmd) {
            return base.Channel.getdata(cmd);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getdataAsync(string cmd) {
            return base.Channel.getdataAsync(cmd);
        }
        
        public string excutedata(string cmd) {
            return base.Channel.excutedata(cmd);
        }
        
        public System.Threading.Tasks.Task<string> excutedataAsync(string cmd) {
            return base.Channel.excutedataAsync(cmd);
        }
    }
}
